### ISSUE TITLE
Add support for Amazon's KMS

### ISSUE THREAD

**Issue by shanewarner** [chef/chef-vault#136]
Having the option to encrypt data using Amazon's new KMS service would be great.

**Comment by jf647** [comment]
What we're calling the 'bootstrap issue' (i.e. having to create the node and wait for it to be indexed before you can update the vault for that node) is what we want to fix for v3.0.0.  I'm going to start collecting thoughts from users on that next week, and having a pluggable fallback mechanism is one of the ideas floating around.

My thought is that if chef-vault supported plugins, then when the vault could not be decrypted using the node's public key, it would iterate through each of the plugins, which would expose a method to indicate whether they should be used (so that people who don't use AWS don't time out trying to hit the endpoint).  If a given plugin should be used, it would provide an implementation to provide the shared secret.

I'd still like to keep the core encryption as Chef Encrypted Data bags, but this would allow us to be infinitely flexible as to how we encrypt the shared secret.

**Comment by sauliusgrigaitis** [comment]
Any update on KMS support?

**Comment by jf647** [comment]
No update in the 2.x branch, no.  We need to do some major surgery to make things pluggable, which is the plan for v3.x.  Prior to breaking things, we need to bring the test coverage up so that we have confidence that 3.x still works in the 2.x use cases.

Any help in that direction (from anyone interested in chef-vault, not calling you out specifically) is welcome.

**Comment by tas50** [comment]
This is very much something we would like to handle natively in Chef Infra Client, but at this point in time we don't plan to expand support to additional stores in the chef-vault project. I'm going to close this out since we won't be working this issue.
