### ISSUE TITLE
Environment Permissions

### ISSUE THREAD

**Issue by ajeba99** [chef/chef-vault#181]
I have a Feature Request ... I think it goes in this Git but may go with Chef itself as well.  I imagine this is a hefty change.

In Chef Vault the process as I understand it ... (simplified)
````
When you add nodes to your environment, they will need to be able to access encrypted data bags.
In order to update a client list for a data bag you must run a knife vault update command.
This will add the node to the data bag's client list and allow the node to decrypt with it's key.
````

Why not just add the functionality to give Environments permissions to data bags?
This would eliminate the need for manually running a knife vault command.  (Manual to me as I run Chef Provisioning)  Also, this would allow my dynamically adjusting environments (in the cloud) to access encrypted data bags without the need for manual intervention.  The node would tell Chef Manage, "Hey I'm in this Environment" ... Chef Manage would say, "This data bag you're trying to access happens to be only available to nodes in that environment." and then they compare keys.

Because sticking a shared key in an S3 bucket just sounds like I am waiting to get hacked.

If this doesn't go here, please let me know where.

**Comment by jf647** [comment]
Nodes can already read all data bags.  chef-vault just uses data bags as a place to store an asymmetrically encrypted (with the node's public key) copy of the encrypted data bag shared secret.

The clients array in the _keys data bag is administrative metadata only - it doesn't restrict who can read the data bag contents.

chef-vault security doesn't come from where the asymmetrically stored copy lives - it could easily live in an environment - but rather that only the node has the private key in order to decrypt the shared secret, which it then uses to decrypt the encrypted data bag.

chef-vault isn't a system for putting access controls on data bags, it's a system for enabling select entities to decrypt encrypted data bags that everyone can read.

**Comment by pburkholder** [comment]
Unfortunately, nodes can lie about their environments. At least until Chef implements https://github.com/chef/chef-rfc/blob/master/rfc045-node_state_separation.md

**Comment by ajeba99** [comment]
Correct, the clients array in the _keys data bag is administrative metadata only - it doesn't restrict who can read the data bag contents but it does restrict which clients can decrypt the data bag. If I am misunderstanding the clients array please set me straight.

I am using the following example knife command ...
````
knife vault update <environment_name> <environment_name> --json ./<environment_name>\<environment_name>.json --search 'chef_environment:<environment_name>'
````
... to update the client list array in order to restrict which clients have the ability to decrypt a data bag.  In the Windows world (insert lol here) this is akin to Group Permissions of which computers can be a member.

I am simply suggesting, eliminate the knife vault update command, to update the client array, and let me put an environment there instead.  I understand that clients can potentially lie about the the environment their in but that's going to be an edge case.  If a node is hacked even the current method isn't more secure.  I am suggesting this for users who manage dynamically changing cloud environments such as myself.

**Comment by jf647** [comment]
Being in the clients array isn't what lets you decrypt the secret.  There's no point where chef or chef-vault says "the user with name x ajeba99 is allowed to decrypt this data bag because clients.key?('ajeba99') is true"

You can try it yourself - remove the entire clients or admins array using `knife data bag edit VAULT ITEM_keys` and then try to decrypt the vault.  It still works, and in fact this is how chef-keepass (the predecessor to chef-vault) worked - it had no metadata and chef-vault can still decrypt vaults created with it.

What lets you decrypt is if unencrypted data bag ITEMNAME_keys has an entry that matches your node name (hostname for servers, username for people), and the value of that key is an asymmetrically encrypted copy of the shared secret encrypted with that person's public key.

There is a file THEORY.md in the root of the repo that explains exactly what happens during creation and encryption, and it may be helpful to read that to understand the mechanics.

Again, there are no ACLs in chef-vault.  I can see your copy of the shared secret and you can see mine, but I can only decrypt mine and you can only decrypt yours.

**Comment by ajeba99** [comment]
Right Thank You for helping me understand the particulars and what is validated by whom in the _keys data bag.  Simply, the clients array is for permissions as the keys beneath the clients array are for decryption.

The request still stands.  A more streamlined solution to decryption management rather than manual intervention by a user to add clients and keys to a data bag.

**Comment by thommay** [comment]
I think this is a WONTFIX for chef-vault; it's simply not the way the application is designed. I fully appreciate that you'd like a more streamlined approach, but if something like that is built it will likely be a separate product.
