### ISSUE TITLE
chef-vault - want to change source from rubygems.org to my own http server

### ISSUE THREAD

**Issue by priyanshuagrawalchef** [chef/chef-vault#300]
Due to security concern we want to install gem on node by getting from my own http server instead of rubygems.org.
I changed the source in Gemfile of chef-vault cookbook but still when running chef-client on node , it refers to rubygems.org to install the gems.
Is this a issue.

we are working on chef client version 13.6.4

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
