### ISSUE TITLE
Databag/DatabagItem  is not encrypted with your public key.  Contact an administrator of the vault item to encrypt for you!

### ISSUE THREAD

**Issue by SrikarshVardhanreddyKolanu** [chef/chef-vault#303]
Created Vault using
knife vault create databag_name databag_item -J databag_file.json -A admin --mode client
Able to create databag item successfully which is encrypted using admin.pem file.
Ran chef-client but it's giving below error
Databag/DatabagItem is not encrypted with your public key. Contact an administrator of the vault item to encrypt for you!
Can anyone please look over this and suggest is there any command I missed?

**Comment by thommay** [comment]
Yes, you've only encrypted this to your admin account, you need to add the clients you want to decrypt it with -C.

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by SrikarshVardhanreddyKolanu** [comment]
@thommay but -C option is not available with knife as stated over here https://github.com/chef/chef-vault/issues/304 .
Could you please suggest how do I use that option ?
