### ISSUE TITLE
Error: invalid option: -C USAGE: knife vault create VAULT ITEM VALUES (options)

### ISSUE THREAD

**Issue by SrikarshVardhanreddyKolanu** [chef/chef-vault#304]
Am trying to create a vault with -C option 
knife vault create databag_name databag_item -J databag_file.json -A admin -S "role:webserver" -C "client1"
 as mentioned here https://docs.chef.io/chef_vault.html but it's returning below error 

Error: invalid option: -C USAGE: knife vault create VAULT ITEM VALUES (options)
USAGE: knife vault create VAULT ITEM VALUES (options)
    -A, --admins ADMINS              Chef users to be added as admins
    -s, --server-url URL             Chef Server URL
        --chef-zero-host HOST        Host to start chef-zero on
        --chef-zero-port PORT        Port (or port range) to start chef-zero on.  Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
    -k, --key KEY                    API Client Key
        --[no-]color                 Use colored output, defaults to enabled
    -c, --config CONFIG              The configuration file to use
        --defaults                   Accept default values for all questions
    -d, --disable-editing            Do not open EDITOR, just accept the data as is
    -e, --editor EDITOR              Set the editor to use for interactive commands
    -E, --environment ENVIRONMENT    Set the Chef environment (except for in searches, where this will be flagrantly ignored)
        --file FILE                  File to be added to vault item as file-content
        --[no-]fips                  Enable fips mode
    -F, --format FORMAT              Which format to use for output
    -J, --json FILE                  File containing JSON data to encrypt
        --[no-]listen                Whether a local mode (-z) server binds to a port
    -z, --local-mode                 Point knife commands at local repository instead of server
    -u, --user USER                  API Client Username
        --print-after                Show the data after a destructive operation
    -S, --search SEARCH              Chef SOLR search for clients
    -M, --mode MODE                  Chef mode to run in default - solo
    -V, --verbose                    More verbose output. Use twice for max verbosity
    -v, --version                    Show chef version
    -y, --yes                        Say yes to all prompts for confirmation
    -h, --help                       Show this message

using this knife -v
Chef: 12.12.15

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
